global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: "nodejs_app"
    static_configs:
      - targets: [ "localhost:9464" ]  # For local development
    metrics_path: "/metrics"

  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'localhost:8889' ]